{
 "title": "Air Quality Index",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-family: sans-serif; text-align: left; padding: 10px; color: #ffeb3b; font-size: 1.5em;\">\n  <h1 style=\"margin-bottom: 0.3em; font-size: 2.4em;\">Jerusalem Air Quality Dashboard</h1>\n  <p style=\"margin: 0.4em 0;\"><strong>Reading:</strong> Latest</p>\n  <p style=\"margin: 0.4em 0;\"><strong>Source:</strong> Israel Ministry of Environmental Protection</p>\n</div>\n"
   }
  },
  { "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 } },
  { "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 } },
  {
   "title": "Jerusalem Urban Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(waqi_aqi{station=~\"Central Bus Station|Sanhedriya|Baka\"})",
     "legendFormat": "PM2.5"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 } },
  { "gridPos": { "h": 12, "w": 10, "x": 0, "y": 8 } },
  { "gridPos": { "h": 12, "w": 13, "x": 10, "y": 8 } },
  {
   "title": "Sanhedriya",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waqi_pm25{station=\"Sanhedriya\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kfar Etsion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waqi_pm25{station=\"Kfar Etzion\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CBS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waqi_pm25{station=\"Central Bus Station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baka",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waqi_pm25{station=\"Baka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tel Aviv Center",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waqi_pm25{station=\"Tel Aviv\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}